apiVersion: v2
name: wazuh
description: Wazuh is a free and open source security platform that unifies XDR and SIEM protection for endpoints and cloud workloads.
type: application
appVersion: 4.11.1
version: 0.0.7
home: https://wazuh.com/
sources:
  - https://github.com/dBildungsplattform/wazuh-helm-chart.git
dependencies:
  - name: cert-manager
    version: 1.17.1
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
